### ISSUE TITLE
Not an issue, but more of an update/proposal/question thing ;)

### ISSUE THREAD

**Issue by wize-wiz** [joshbrw/laravel-module-installer#20]
@joshbrw 

I've noticed your commit history and you're secretly still active ;)

I've [created a fork](https://github.com/wize-wiz/laravel-module-installer) and updated/refactored some parts most current PR's talk about. Update the tests using PHPUnit 11 and brought those tests up to date.

If by change there is any interest to bring this package up to date, we could go through the changes (it isn't that much). The readme is up to date on the changes it brings.

If the interest is just mine, don't feel bothered and have a good day :)

Cheers.

**Comment by joshbrw** [comment]
Hi @wize-wiz,

Thanks for this.

You're right - I am active, but I only work on commercial work now. I originally created this project to assist me in a commercial project. 

If you're happy to maintain this, I can mark this project as abandoned with your repo as the suggested alternative.

Thanks

**Comment by wize-wiz** [comment]
@joshbrw 

> You're right - I am active, but I only work on commercial work now. I originally created this project to assist me in a > commercial project.

That's good to know.

> If you're happy to maintain this, I can mark this project as abandoned with your repo as the suggested alternative.

Hmm I wasn't really aiming to replace your repository with mine and I don't think it's a solution that will last. This package in its current state does its job very well but can't really do much, which seems to be fine for a lot of folks :)

After posting my suggestion to get this package to do a little bit more, I started writing my own version using this package as a starting point. I will commit my last changes to my fork and then I will work on my own version on gitlab. You can do with my fork whatever you want.

Your package was mentioned in some topic called [Publishing modules](https://laravelmodules.com/docs/v11/publishing-modules) to auto-install modules using `composer require`. Here I got the idea these two packages somehow work together.

The only solution I see is to incorporate this package in `nwidart/laravel-modules` and then you can abandon this repo ;)

Thanks for your reply and cheers!
