### ISSUE TITLE
Module package is not copied to Module directory

### ISSUE THREAD

**Issue by rexybytes** [joshbrw/laravel-module-installer#3]
I have created a Laravel module using Nwidart Modules package. I followed the steps mentioned in [here](https://nwidart.com/laravel-modules/v2/advanced-tools/publishing-modules). 
The package's composer.json looks like this:
`{
    "name": "namespace/test",
    "description": "",
    "type" : "laravel-module",
    "autoload": {
        "psr-4": {
            "Modules\\Test\\": ""
            "Joshbrw\\LaravelModuleInstaller\\": "src/"
        }
    },
    "require": {
        "joshbrw/laravel-module-installer": "^0.1.2"
    }
}`

I installed "joshbrw/laravel-module-installer" in the main project. However, when I install the package using `composer install namespace/test` , it gets installed inside vendor/ and not inside Modules/ as expected.

**Comment by joshbrw** [comment]
@rexybytes You have to set the `type` to `laravel-module` in your module package, and ensure that the `name` is in format `<namespace>/<moduleName>-module`, for example `joshbrw/user-module` would be installed as `Modules/User`

**Comment by rexybytes** [comment]
@joshbrw Yes, that worked! Thank you.

**Comment by joshbrw** [comment]
Glad to hear @rexybytes - will make sure I write some proper documentation at some point soon!
