### ISSUE TITLE
Install from private repository not on Packagist

### ISSUE THREAD

**Issue by emperorjm** [joshbrw/laravel-module-installer#5]
I want to create my Modules as private packages within Bitbucket and be able to install and update my packages using your package. Is this possible and if it is can you give some guidance as to how to go about implementing this solution?

**Comment by nasirkhan** [comment]
@emperorjm did you find any solution for your query?

**Comment by joshbrw** [comment]
@nasirkhan @emperorjm You can use Composer's VCS Repositories for this; https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by nasirkhan** [comment]
thanks @joshbrw  for sharing the doc. By the time i added the comment i found an another related doc for private packages https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md. 

do you have any plan t easily integrate these features?

**Comment by joshbrw** [comment]
@nasirkhan There are no features to implement on my side - it's simply a case of putting your custom module into a git repository somewhere, referencing it in your `require` section of your `composer.json` and adding it as a `vcs` repository in your `composer.json`.
